CREATE TABLE [dbo].[TBL_GSTR2_B2BUR] (
    [b2burid] INT IDENTITY (1, 1) NOT NULL,
    [gstr2id] INT NOT NULL,
    [gstinid] INT NULL,
    CONSTRAINT [PK_TBL_GSTR2_B2BUR] PRIMARY KEY CLUSTERED ([b2burid] ASC),
    CONSTRAINT [FK_TBL_GSTR2_B2BUR_TBL_GSTR2] FOREIGN KEY ([gstr2id]) REFERENCES [dbo].[TBL_GSTR2] ([gstr2id])
);

