CREATE TABLE [dbo].[TBL_GSTR1_CDNR_NT_ITMS] (
    [itmsid]  INT IDENTITY (1, 1) NOT NULL,
    [ntid]    INT NOT NULL,
    [num]     INT NULL,
    [gstinid] INT NULL,
    [gstr1id] INT NULL,
    PRIMARY KEY CLUSTERED ([itmsid] ASC),
    CONSTRAINT [FK_TBL_GSTR1_CDNR_NT_ITMS_TBL_GSTR1_CDNR_NT] FOREIGN KEY ([ntid]) REFERENCES [dbo].[TBL_GSTR1_CDNR_NT] ([ntid])
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_TBL_GSTR1_CDNR_NT_ITMS_0E48DDBCAF6CB239CC4428656C098FFA]
    ON [dbo].[TBL_GSTR1_CDNR_NT_ITMS]([ntid] ASC, [num] ASC);

