CREATE TABLE [dbo].[TBL_GSTR2_B2B_INV] (
    [invid]        INT             IDENTITY (1, 1) NOT NULL,
    [b2bid]        INT             NOT NULL,
    [chksum]       VARCHAR (64)    NULL,
    [inum]         VARCHAR (50)    NULL,
    [idt]          VARCHAR (50)    NULL,
    [val]          DECIMAL (18, 2) NULL,
    [flag]         VARCHAR (1)     NULL,
    [rchrg]        VARCHAR (1)     NULL,
    [pos]          VARCHAR (2)     NULL,
    [inv_typ]      VARCHAR (5)     NULL,
    [gstinid]      INT             NULL,
    [gstr2id]      INT             NULL,
    [uploadStatus] VARCHAR (1)     NULL,
    [createddate]  DATETIME        NULL,
    [createdby]    INT             NULL,
    [custid]       INT             NULL,
    [CompCode]     VARCHAR (50)    NULL,
    [UnitCode]     VARCHAR (50)    NULL,
    [ReceivedBy]   VARCHAR (50)    NULL,
    [ReceivedDate] VARCHAR (10)    NULL,
    CONSTRAINT [PK_TBL_GSTR2_B2B_INV] PRIMARY KEY CLUSTERED ([invid] ASC),
    CONSTRAINT [FK_TBL_GSTR2_B2B_INV_TBL_GSTR2_B2B] FOREIGN KEY ([b2bid]) REFERENCES [dbo].[TBL_GSTR2_B2B] ([b2bid])
);

