CREATE TABLE [dbo].[TBL_Customer] (
    [CustId]       INT            IDENTITY (1, 1) NOT NULL,
    [Name]         VARCHAR (50)   NOT NULL,
    [Designation]  VARCHAR (50)   NULL,
    [Company]      NVARCHAR (250) NULL,
    [GSTINNo]      VARCHAR (50)   NOT NULL,
    [Email]        VARCHAR (50)   NOT NULL,
    [MobileNo]     VARCHAR (50)   NOT NULL,
    [PANNo]        VARCHAR (50)   NOT NULL,
    [Statecode]    VARCHAR (50)   NOT NULL,
    [ValidFrom]    DATETIME       NULL,
    [ValidTo]      DATETIME       NULL,
    [StatusCode]   INT            NOT NULL,
    [CreatedDate]  DATETIME       NULL,
    [ModifiedBy]   INT            NULL,
    [ModifiedDate] DATETIME       NULL,
    [RowStatus]    BIT            NULL,
    [Approvedby]   INT            NULL,
    [ApprovedDate] DATETIME       NULL,
    [ReferenceNo]  VARCHAR (50)   NULL,
    [AadharNo]     VARCHAR (12)   NULL,
    [Address]      NVARCHAR (MAX) NULL,
    [TRPId]        INT            NULL,
    [PackageId]    INT            NULL,
    [createdby]    INT            NULL,
    [Oracle_Id]    INT            NULL,
    [PartnerId]    INT            NULL,
    CONSTRAINT [PK_TBL_Customer] PRIMARY KEY CLUSTERED ([CustId] ASC),
    CONSTRAINT [FK_TBL_Customer_StatusMaster] FOREIGN KEY ([StatusCode]) REFERENCES [dbo].[StatusMaster] ([StatusCode])
);

