CREATE TABLE [dbo].[TBL_EXT_GSTR1_EXPA_INV] (
    [invid]           INT             IDENTITY (1, 1) NOT NULL,
    [gstin]           VARCHAR (15)    NULL,
    [fp]              VARCHAR (10)    NULL,
    [gt]              DECIMAL (18, 2) NULL,
    [cur_gt]          DECIMAL (18, 2) NULL,
    [exp_typ]         VARCHAR (5)     NULL,
    [flag]            VARCHAR (1)     NULL,
    [chksum]          VARCHAR (75)    NULL,
    [oinum]           VARCHAR (50)    NULL,
    [oidt]            VARCHAR (50)    NULL,
    [inum]            VARCHAR (50)    NULL,
    [idt]             VARCHAR (50)    NULL,
    [val]             DECIMAL (18, 2) NULL,
    [sbpcode]         VARCHAR (6)     NULL,
    [sbnum]           VARCHAR (50)    NULL,
    [sbdt]            VARCHAR (50)    NULL,
    [txval]           DECIMAL (18, 2) NULL,
    [rt]              DECIMAL (18, 2) NULL,
    [iamt]            DECIMAL (18, 2) NULL,
    [rowstatus]       TINYINT         NULL,
    [sourcetype]      VARCHAR (15)    NULL,
    [referenceno]     VARCHAR (50)    NULL,
    [createddate]     DATETIME        NULL,
    [errormessage]    VARCHAR (255)   NULL,
    [fileid]          INT             NULL,
    [hsncode]         VARCHAR (50)    NULL,
    [hsndesc]         VARCHAR (255)   NULL,
    [qty]             DECIMAL (18, 2) NULL,
    [unitprice]       DECIMAL (18, 2) NULL,
    [discount]        DECIMAL (18, 2) NULL,
    [ispdfgenerated]  BIT             NULL,
    [uqc]             VARCHAR (50)    NULL,
    [Addinfo]         VARCHAR (MAX)   NULL,
    [ShippingAddress] VARCHAR (MAX)   NULL,
    [createdby]       INT             NULL,
    [buyerid]         INT             NULL,
    [ReceiverName]    VARCHAR (250)   NULL,
    [diff_percent]    DECIMAL (4, 2)  NULL,
    [csamt]           DECIMAL (18, 2) NULL,
    PRIMARY KEY CLUSTERED ([invid] ASC)
);

