CREATE TABLE [dbo].[TBL_EXT_EWB_GENERATION] (
    [ewbid]            INT             IDENTITY (1, 1) NOT NULL,
    [userGSTIN]        NVARCHAR (15)   NULL,
    [supplyType]       NVARCHAR (15)   NULL,
    [subSupplyType]    NVARCHAR (15)   NULL,
    [docType]          NVARCHAR (15)   NULL,
    [docNo]            NVARCHAR (50)   NULL,
    [docDate]          NVARCHAR (10)   NULL,
    [fromGstin]        NVARCHAR (15)   NULL,
    [fromTrdName]      NVARCHAR (100)  NULL,
    [fromAddr1]        NVARCHAR (MAX)  NULL,
    [fromAddr2]        NVARCHAR (MAX)  NULL,
    [fromPlace]        NVARCHAR (50)   NULL,
    [fromPinCode]      INT             NULL,
    [fromStateCode]    INT             NULL,
    [actFromStateCode] INT             NULL,
    [toGstin]          NVARCHAR (15)   NULL,
    [toTrdName]        NVARCHAR (100)  NULL,
    [toAddr1]          NVARCHAR (MAX)  NULL,
    [toAddr2]          NVARCHAR (MAX)  NULL,
    [toPlace]          NVARCHAR (50)   NULL,
    [toPincode]        INT             NULL,
    [toStateCode]      INT             NULL,
    [actToStateCode]   INT             NULL,
    [totalValue]       DECIMAL (18, 2) NULL,
    [cgstValue]        DECIMAL (18, 2) NULL,
    [sgstValue]        DECIMAL (18, 2) NULL,
    [igstValue]        DECIMAL (18, 2) NULL,
    [cessValue]        DECIMAL (18, 2) NULL,
    [totinvvalue]      DECIMAL (18, 2) NULL,
    [transMode]        INT             NULL,
    [transDistance]    NVARCHAR (50)   NULL,
    [transporterId]    NVARCHAR (15)   NULL,
    [transporterName]  NVARCHAR (100)  NULL,
    [transDocNo]       NVARCHAR (15)   NULL,
    [transDocDate]     NVARCHAR (10)   NULL,
    [vehicleNo]        NVARCHAR (20)   NULL,
    [vehicleType]      NVARCHAR (50)   NULL,
    [productName]      NVARCHAR (100)  NULL,
    [productDesc]      NVARCHAR (MAX)  NULL,
    [hsnCode]          NVARCHAR (50)   NULL,
    [quantity]         DECIMAL (18, 2) NULL,
    [qtyUnit]          NVARCHAR (10)   NULL,
    [taxableAmount]    DECIMAL (18, 2) NULL,
    [cgstRate]         DECIMAL (18, 2) NULL,
    [sgstRate]         DECIMAL (18, 2) NULL,
    [igstRate]         DECIMAL (18, 2) NULL,
    [cessRate]         DECIMAL (18, 2) NULL,
    [cessAdvol]        DECIMAL (18, 2) NULL,
    [ewayBillNo]       NVARCHAR (50)   NULL,
    [ewayBillDate]     NVARCHAR (50)   NULL,
    [rowstatus]        TINYINT         NULL,
    [sourcetype]       VARCHAR (15)    NULL,
    [referenceno]      VARCHAR (50)    NULL,
    [createdby]        INT             NULL,
    [createddate]      DATETIME        NULL,
    [errorCodes]       NVARCHAR (200)  NULL,
    [errormessage]     VARCHAR (255)   NULL,
    [fileid]           INT             NULL,
    [BranchId]         INT             NULL,
    [APIBulkFlag]      VARCHAR (1)     NULL,
    [ReferenceId]      NVARCHAR (250)  NULL,
    [InvoiceType]      NVARCHAR (10)   NULL
);





