CREATE TABLE [dbo].[TBL_CSV_GSTR6_RECS] (
    [fileid]       INT           NULL,
    [slno]         VARCHAR (50)  NULL,
    [doctype]      VARCHAR (50)  NULL,
    [cpty]         VARCHAR (50)  NULL,
    [fp]           VARCHAR (50)  NULL,
    [typ]          VARCHAR (64)  NULL,
    [ctin]         VARCHAR (50)  NULL,
    [isd_docty]    VARCHAR (50)  NULL,
    [docnum]       VARCHAR (16)  NULL,
    [docdt]        VARCHAR (50)  NULL,
    [elglst]       VARCHAR (50)  NULL,
    [iamti]        VARCHAR (50)  NULL,
    [iamts]        VARCHAR (50)  NULL,
    [iamtc]        VARCHAR (50)  NULL,
    [samts]        VARCHAR (50)  NULL,
    [samti]        VARCHAR (50)  NULL,
    [camti]        VARCHAR (50)  NULL,
    [camtc]        VARCHAR (50)  NULL,
    [rt]           VARCHAR (50)  NULL,
    [txval]        VARCHAR (50)  NULL,
    [iamt]         VARCHAR (50)  NULL,
    [camt]         VARCHAR (50)  NULL,
    [samt]         VARCHAR (50)  NULL,
    [csamt]        VARCHAR (50)  NULL,
    [totval]       VARCHAR (50)  NULL,
    [statecd]      VARCHAR (2)   NULL,
    [ntty]         VARCHAR (50)  NULL,
    [nt_num]       VARCHAR (50)  NULL,
    [nt_dt]        VARCHAR (50)  NULL,
    [rcpty]        VARCHAR (15)  NULL,
    [odocnum]      VARCHAR (10)  NULL,
    [odocdt]       VARCHAR (50)  NULL,
    [ont_num]      VARCHAR (50)  NULL,
    [ont_dt]       VARCHAR (50)  NULL,
    [rstatecd]     VARCHAR (2)   NULL,
    [errorcode]    SMALLINT      NULL,
    [errormessage] VARCHAR (255) NULL
);

