CREATE TABLE [dbo].[TBL_EXT_GSTR6_ISD] (
    [isdid]        INT             IDENTITY (1, 1) NOT NULL,
    [gstin]        VARCHAR (15)    NULL,
    [fp]           VARCHAR (10)    NULL,
    [flag]         VARCHAR (1)     NULL,
    [chksum]       VARCHAR (75)    NULL,
    [typ]          VARCHAR (64)    NULL,
    [cpty]         VARCHAR (15)    NULL,
    [statecd]      VARCHAR (2)     NULL,
    [isd_docty]    VARCHAR (60)    NULL,
    [docnum]       VARCHAR (16)    NULL,
    [docdt]        VARCHAR (50)    NULL,
    [crdnum]       VARCHAR (16)    NULL,
    [crddt]        VARCHAR (50)    NULL,
    [iamti]        DECIMAL (11, 2) NULL,
    [iamts]        DECIMAL (11, 2) NULL,
    [iamtc]        DECIMAL (11, 2) NULL,
    [samts]        DECIMAL (11, 2) NULL,
    [samti]        DECIMAL (11, 2) NULL,
    [camti]        DECIMAL (11, 2) NULL,
    [camtc]        DECIMAL (11, 2) NULL,
    [csamt]        DECIMAL (11, 2) NULL,
    [rowstatus]    TINYINT         NULL,
    [sourcetype]   VARCHAR (15)    NULL,
    [referenceno]  VARCHAR (50)    NULL,
    [createddate]  DATETIME        NULL,
    [errormessage] VARCHAR (255)   NULL,
    [fileid]       INT             NULL,
    [CompCode]     VARCHAR (50)    NULL,
    [UnitCode]     VARCHAR (50)    NULL,
    [ReceivedBy]   VARCHAR (50)    NULL,
    [ReceivedDate] VARCHAR (10)    NULL,
    PRIMARY KEY CLUSTERED ([isdid] ASC)
);

