CREATE TABLE [dbo].[TBL_GSTR_TYPE] (
    [GSTRId]   INT          IDENTITY (1, 1) NOT NULL,
    [GSTRName] VARCHAR (50) NULL,
    CONSTRAINT [PK_TBL_GSTR_TYPE] PRIMARY KEY CLUSTERED ([GSTRId] ASC)
);

