CREATE TABLE [dbo].[TBL_EXT_GSTR6_CDNA] (
    [cdnaid]       INT             IDENTITY (1, 1) NOT NULL,
    [gstin]        VARCHAR (15)    NULL,
    [fp]           VARCHAR (10)    NULL,
    [ctin]         VARCHAR (15)    NULL,
    [flag]         VARCHAR (1)     NULL,
    [chksum]       VARCHAR (75)    NULL,
    [nt_num]       VARCHAR (50)    NULL,
    [nt_dt]        VARCHAR (50)    NULL,
    [ont_num]      VARCHAR (50)    NULL,
    [ont_dt]       VARCHAR (50)    NULL,
    [inum]         VARCHAR (50)    NULL,
    [idt]          VARCHAR (50)    NULL,
    [ntty]         VARCHAR (1)     NULL,
    [rt]           DECIMAL (11, 2) NULL,
    [txval]        DECIMAL (11, 2) NULL,
    [iamt]         DECIMAL (11, 2) NULL,
    [camt]         DECIMAL (11, 2) NULL,
    [samt]         DECIMAL (11, 2) NULL,
    [csamt]        DECIMAL (11, 2) NULL,
    [rowstatus]    TINYINT         NULL,
    [sourcetype]   VARCHAR (15)    NULL,
    [referenceno]  VARCHAR (50)    NULL,
    [createddate]  DATETIME        NULL,
    [errormessage] VARCHAR (255)   NULL,
    [fileid]       INT             NULL,
	val Decimal(18,2) NULL,
    PRIMARY KEY CLUSTERED ([cdnaid] ASC)
);

