CREATE TABLE [dbo].[TBL_EWB_GENERATION] (
    [ewbid]                INT             IDENTITY (1, 1) NOT NULL,
    [userGSTIN]            NVARCHAR (50)   NULL,
    [supplyType]           NVARCHAR (1)    NULL,
    [subSupplyType]        NVARCHAR (2)    NULL,
    [docType]              NVARCHAR (3)    NULL,
    [docNo]                NVARCHAR (50)   NULL,
    [docDate]              VARCHAR (30)    NULL,
    [fromGstin]            NVARCHAR (15)   NULL,
    [fromTrdName]          NVARCHAR (100)  NULL,
    [fromAddr1]            NVARCHAR (MAX)  NULL,
    [fromAddr2]            NVARCHAR (MAX)  NULL,
    [fromPlace]            NVARCHAR (50)   NULL,
    [fromPinCode]          INT             NULL,
    [fromStateCode]        INT             NULL,
    [actFromStateCode]     INT             NULL,
    [toGstin]              NVARCHAR (15)   NULL,
    [toTrdName]            NVARCHAR (100)  NULL,
    [toAddr1]              NVARCHAR (MAX)  NULL,
    [toAddr2]              NVARCHAR (MAX)  NULL,
    [toPlace]              NVARCHAR (50)   NULL,
    [toPincode]            INT             NULL,
    [toStateCode]          INT             NULL,
    [actToStateCode]       INT             NULL,
    [totalValue]           DECIMAL (18, 2) NULL,
    [igstValue]            DECIMAL (18, 2) NULL,
    [cgstValue]            DECIMAL (18, 2) NULL,
    [sgstValue]            DECIMAL (18, 2) NULL,
    [cessValue]            DECIMAL (18, 2) NULL,
    [totinvvalue]          DECIMAL (18, 2) NULL,
    [transMode]            INT             NULL,
    [transDistance]        NVARCHAR (50)   NULL,
    [transporterId]        NVARCHAR (15)   NULL,
    [transporterName]      NVARCHAR (100)  NULL,
    [transDocNo]           NVARCHAR (15)   NULL,
    [transDocDate]         VARCHAR (30)    NULL,
    [vehicleNo]            NVARCHAR (20)   NULL,
    [vehicleType]          NVARCHAR (10)   NULL,
    [CustId]               INT             NULL,
    [CreatedBy]            INT             NULL,
    [CreatedDate]          DATETIME        NULL,
    [ModifiedBy]           INT             NULL,
    [ModifiedDate]         DATETIME        NULL,
    [flag]                 NVARCHAR (1)    NULL,
    [EWB_status]           INT             NULL,
    [ewayBillNo]           NVARCHAR (50)   NULL,
    [ewayBillDate]         NVARCHAR (50)   NULL,
    [validUpto]            NVARCHAR (50)   NULL,
    [EWB_errorCodes]       NVARCHAR (20)   NULL,
    [EWB_errorDescription] NVARCHAR (MAX)  NULL,
    [cancelRsnCode]        INT             NULL,
    [cancelRmrk]           NVARCHAR (50)   NULL,
    [cancelDate]           NVARCHAR (30)   NULL,
    [CAN_status]           INT             NULL,
    [CAN_errorCodes]       NVARCHAR (20)   NULL,
    [CAN_errorDescription] NVARCHAR (MAX)  NULL,
    [status]               NVARCHAR (10)   NULL,
    [genMode]              NVARCHAR (50)   NULL,
    [extendedTimes]        INT             NULL,
    [rejectStatus]         NVARCHAR (10)   NULL,
    [ewbRejectedDate]      NVARCHAR (20)   NULL,
    [BranchId]             INT             NULL,
    [APIBulkFlag]          VARCHAR (1)     NULL,
    [noValidDays]          INT             NULL,
    [ReferenceId]          NVARCHAR (250)  NULL,
    CONSTRAINT [PK_TBL_EWB_GENERATION] PRIMARY KEY CLUSTERED ([ewbid] ASC)
);



