CREATE TABLE [dbo].[TBL_GSTR6_CDNRA_NT_ITMS] (
    [itmsid]  INT IDENTITY (1, 1) NOT NULL,
    [invid]   INT NOT NULL,
    [num]     INT NULL,
    [gstinid] INT NULL,
    [gstr6id] INT NULL,
    CONSTRAINT [PK_TBL_GSTR6_CDNRA_NT_ITMS] PRIMARY KEY CLUSTERED ([itmsid] ASC),
    CONSTRAINT [FK_TBL_GSTR6_CDNRA_NT_ITMS_TBL_GSTR6_CDNRA_NT] FOREIGN KEY ([invid]) REFERENCES [dbo].[TBL_GSTR6_CDNRA_NT] ([invid])
);

