CREATE TABLE [dbo].[TBL_CSV_EWB_GEN_RECS] (
    [fileid]           INT            NULL,
    [slno]             VARCHAR (50)   NULL,
    [supplytype]       VARCHAR (50)   NULL,
    [subsupplytype]    VARCHAR (50)   NULL,
    [doctype]          VARCHAR (50)   NULL,
    [docno]            VARCHAR (50)   NULL,
    [docdate]          VARCHAR (50)   NULL,
    [fromgstin]        VARCHAR (50)   NULL,
    [fromtrdname]      VARCHAR (50)   NULL,
    [fromaddr1]        VARCHAR (50)   NULL,
    [fromaddr2]        VARCHAR (50)   NULL,
    [fromplace]        VARCHAR (50)   NULL,
    [frompincode]      VARCHAR (50)   NULL,
    [fromstatecode]    VARCHAR (50)   NULL,
    [actfromstatecode] VARCHAR (50)   NULL,
    [togstin]          VARCHAR (50)   NULL,
    [totrdname]        VARCHAR (50)   NULL,
    [toaddr1]          VARCHAR (50)   NULL,
    [toaddr2]          VARCHAR (50)   NULL,
    [toplace]          VARCHAR (50)   NULL,
    [topincode]        VARCHAR (50)   NULL,
    [tostatecode]      VARCHAR (50)   NULL,
    [acttostatecode]   VARCHAR (50)   NULL,
    [totalvalue]       VARCHAR (50)   NULL,
    [igstvalue]        VARCHAR (50)   NULL,
    [cgstvalue]        VARCHAR (50)   NULL,
    [sgstvalue]        VARCHAR (50)   NULL,
    [cessvalue]        VARCHAR (50)   NULL,
    [totinvvalue]      VARCHAR (50)   NULL,
    [transmode]        VARCHAR (50)   NULL,
    [transdistance]    VARCHAR (50)   NULL,
    [transporterid]    VARCHAR (50)   NULL,
    [transportername]  VARCHAR (50)   NULL,
    [transdocno]       VARCHAR (50)   NULL,
    [transdocdate]     VARCHAR (50)   NULL,
    [vehicleno]        VARCHAR (50)   NULL,
    [vehicletype]      VARCHAR (250)  NULL,
    [productname]      VARCHAR (250)  NULL,
    [productdesc]      VARCHAR (250)  NULL,
    [hsncode]          VARCHAR (50)   NULL,
    [quantity]         VARCHAR (50)   NULL,
    [qtyunit]          VARCHAR (50)   NULL,
    [taxableamount]    VARCHAR (50)   NULL,
    [igstrate]         VARCHAR (50)   NULL,
    [cgstrate]         VARCHAR (50)   NULL,
    [sgstrate]         VARCHAR (50)   NULL,
    [cessrate]         VARCHAR (50)   NULL,
    [cessadvol]        VARCHAR (50)   NULL,
    [branch]           NVARCHAR (250) NULL,
    [InvoiceType]      VARCHAR (50)   NULL,
    [AllowDuplication] VARCHAR (50)   NULL,
    [errorcode]        SMALLINT       NULL,
    [errormessage]     VARCHAR (255)  NULL
);





