CREATE TABLE [dbo].[TBL_GSTR6_ISD_INELGLST_DOCLST] (
    [inelgdocid]   INT             IDENTITY (1, 1) NOT NULL,
    [inelgid]      INT             NOT NULL,
    [chksum]       VARCHAR (64)    NULL,
    [flag]         VARCHAR (1)     NULL,
    [isd_docty]    VARCHAR (60)    NULL,
    [docnum]       VARCHAR (16)    NULL,
    [docdt]        VARCHAR (50)    NULL,
    [crdnum]       VARCHAR (16)    NULL,
    [crddt]        VARCHAR (50)    NULL,
    [iamti]        DECIMAL (11, 2) NULL,
    [iamts]        DECIMAL (11, 2) NULL,
    [iamtc]        DECIMAL (11, 2) NULL,
    [samts]        DECIMAL (11, 2) NULL,
    [samti]        DECIMAL (11, 2) NULL,
    [camti]        DECIMAL (11, 2) NULL,
    [camtc]        DECIMAL (11, 2) NULL,
    [csamt]        DECIMAL (11, 2) NULL,
    [gstinid]      INT             NULL,
    [gstr6id]      INT             NULL,
    [createddate]  DATETIME        NULL,
    [createdby]    INT             NULL,
    [custid]       INT             NULL,
    [CompCode]     VARCHAR (50)    NULL,
    [UnitCode]     VARCHAR (50)    NULL,
    [ReceivedBy]   VARCHAR (50)    NULL,
    [ReceivedDate] VARCHAR (10)    NULL,
    CONSTRAINT [PK_TBL_GSTR6_ISD_INELGLST_DOCLST] PRIMARY KEY CLUSTERED ([inelgdocid] ASC),
    CONSTRAINT [FK_TBL_GSTR6_ISD_INELGLST_DOCLST_TBL_GSTR6_ISD_INELGLST] FOREIGN KEY ([inelgid]) REFERENCES [dbo].[TBL_GSTR6_ISD_INELGLST] ([inelgid])
);

