CREATE TABLE [dbo].[TBL_GSTR1_B2B] (
    [b2bid]   INT          IDENTITY (1, 1) NOT NULL,
    [gstr1id] INT          NOT NULL,
    [ctin]    VARCHAR (15) NULL,
    [gstinid] INT          NULL,
    CONSTRAINT [PK_TBL_GSTR1_B2B] PRIMARY KEY CLUSTERED ([b2bid] ASC),
    CONSTRAINT [FK_TBL_GSTR1_B2B_TBL_GSTR1] FOREIGN KEY ([gstr1id]) REFERENCES [dbo].[TBL_GSTR1] ([gstr1id])
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_TBL_GSTR1_B2B_5D141D7DB66ADF7C34B8EE952C4689A3]
    ON [dbo].[TBL_GSTR1_B2B]([gstr1id] ASC, [ctin] ASC);

