CREATE TABLE [dbo].[TBL_GSTR1_B2CS_INV_ITMS] (
    [itmsid]  INT IDENTITY (1, 1) NOT NULL,
    [invid]   INT NOT NULL,
    [num]     INT NULL,
    [gstinid] INT NULL,
    [gstr1id] INT NULL,
    CONSTRAINT [PK_TBL_GSTR1_B2CS_INV_ITMS] PRIMARY KEY CLUSTERED ([itmsid] ASC),
    CONSTRAINT [FK_TBL_GSTR1_B2CS_INV_ITMS_TBL_GSTR1_B2CS_INV] FOREIGN KEY ([invid]) REFERENCES [dbo].[TBL_GSTR1_B2CS_INV] ([invid])
);


GO
CREATE NONCLUSTERED INDEX [nci_wi_TBL_GSTR1_B2CS_INV_ITMS_B5261E0D2B2639D622B669AC9CE1A411]
    ON [dbo].[TBL_GSTR1_B2CS_INV_ITMS]([invid] ASC, [num] ASC);

