//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Resources
    {
        public int Resource_ID { get; set; }
        public string Resource_Name { get; set; }
        public string Resource_Display_Name { get; set; }
        public string Resource_Page_Name { get; set; }
        public byte Resource_MenuItem_ID { get; set; }
        public Nullable<int> FK_Parent_Resource_ID { get; set; }
    }
}
