//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Roles_Resources
    {
        public short Role_Resource_ID { get; set; }
        public int FK_Role_Resource_Role_ID { get; set; }
        public int FK_Role_Resource_Resource_ID { get; set; }
        public bool Role_Resource_IsAssigned { get; set; }
    }
}
