//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Cust_GSTIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Cust_GSTIN()
        {
            this.UserAccess_GSTIN = new HashSet<UserAccess_GSTIN>();
        }
    
        public int GSTINId { get; set; }
        public string GSTINNo { get; set; }
        public string Statecode { get; set; }
        public string PANNo { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> rowstatus { get; set; }
        public string GSTINUserName { get; set; }
        public string Address { get; set; }
        public string EWBUserId { get; set; }
        public string EWBUserName { get; set; }
        public string EWBPassword { get; set; }
    
        public virtual TBL_Customer TBL_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccess_GSTIN> UserAccess_GSTIN { get; set; }
    }
}
