//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Customer()
        {
            this.TBL_Cust_GSTIN = new HashSet<TBL_Cust_GSTIN>();
            this.UserAccess_GSTIN = new HashSet<UserAccess_GSTIN>();
            this.UserLists = new HashSet<UserList>();
            this.TBL_HSN_MASTER = new HashSet<TBL_HSN_MASTER>();
        }
    
        public int CustId { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Company { get; set; }
        public string GSTINNo { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string PANNo { get; set; }
        public string Statecode { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public int StatusCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> RowStatus { get; set; }
        public Nullable<int> Approvedby { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ReferenceNo { get; set; }
        public string AadharNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> TRPId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> Oracle_Id { get; set; }
        public Nullable<bool> WalletPack { get; set; }
        public string LogoPath { get; set; }
        public string supportRefId { get; set; }
    
        public virtual StatusMaster StatusMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Cust_GSTIN> TBL_Cust_GSTIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccess_GSTIN> UserAccess_GSTIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserList> UserLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HSN_MASTER> TBL_HSN_MASTER { get; set; }
    }
}
