//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXT_GSTR1_B2CSA
    {
        public int invid { get; set; }
        public string gstin { get; set; }
        public string fp { get; set; }
        public Nullable<decimal> gt { get; set; }
        public Nullable<decimal> cur_gt { get; set; }
        public string flag { get; set; }
        public string chksum { get; set; }
        public string omon { get; set; }
        public string oty { get; set; }
        public string opos { get; set; }
        public string sply_ty { get; set; }
        public Nullable<decimal> txval { get; set; }
        public string typ { get; set; }
        public string etin { get; set; }
        public string pos { get; set; }
        public Nullable<decimal> rt { get; set; }
        public Nullable<decimal> iamt { get; set; }
        public Nullable<decimal> camt { get; set; }
        public Nullable<decimal> samt { get; set; }
        public Nullable<decimal> csamt { get; set; }
        public Nullable<byte> rowstatus { get; set; }
        public string sourcetype { get; set; }
        public string referenceno { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string errormessage { get; set; }
    }
}
