//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXT_GSTR2_IMPG_INV
    {
        public int impgid { get; set; }
        public string gstin { get; set; }
        public string fp { get; set; }
        public string flag { get; set; }
        public string chksum { get; set; }
        public string is_sez { get; set; }
        public string stin { get; set; }
        public string boe_num { get; set; }
        public string boe_dt { get; set; }
        public Nullable<decimal> boe_val { get; set; }
        public Nullable<decimal> rt { get; set; }
        public Nullable<decimal> txval { get; set; }
        public Nullable<decimal> iamt { get; set; }
        public Nullable<decimal> csamt { get; set; }
        public string elg { get; set; }
        public Nullable<decimal> tx_i { get; set; }
        public Nullable<decimal> tx_cs { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<byte> rowstatus { get; set; }
        public string sourcetype { get; set; }
        public string referenceno { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string errormessage { get; set; }
        public Nullable<int> fileid { get; set; }
        public string hsncode { get; set; }
        public string hsndesc { get; set; }
        public string uqc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string port_code { get; set; }
        public string CompCode { get; set; }
        public string UnitCode { get; set; }
        public string ReceivedBy { get; set; }
        public string ReceivedDate { get; set; }
        public Nullable<int> createdby { get; set; }
    }
}
