//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXT_GSTR1_B2CS_INV
    {
        public int invid { get; set; }
        public string gstin { get; set; }
        public string fp { get; set; }
        public string sply_typ { get; set; }
        public string typ { get; set; }
        public Nullable<decimal> gt { get; set; }
        public Nullable<decimal> cur_gt { get; set; }
        public string pos { get; set; }
        public string flag { get; set; }
        public string chksum { get; set; }
        public string inum { get; set; }
        public string idt { get; set; }
        public Nullable<decimal> val { get; set; }
        public string etin { get; set; }
        public Nullable<decimal> rt { get; set; }
        public Nullable<decimal> txval { get; set; }
        public Nullable<decimal> iamt { get; set; }
        public Nullable<decimal> camt { get; set; }
        public Nullable<decimal> samt { get; set; }
        public Nullable<decimal> csamt { get; set; }
        public Nullable<byte> rowstatus { get; set; }
        public string sourcetype { get; set; }
        public string referenceno { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string errormessage { get; set; }
        public Nullable<int> fileid { get; set; }
        public string hsncode { get; set; }
        public string hsndesc { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<bool> ispdfgenerated { get; set; }
        public Nullable<int> buyerid { get; set; }
        public string uqc { get; set; }
        public Nullable<int> createdby { get; set; }
        public string itemdescription { get; set; }
        public string Addinfo { get; set; }
        public string CompCode { get; set; }
        public string UnitCode { get; set; }
        public string GoodsAndService { get; set; }
        public string TransportMode { get; set; }
        public string vehicleNo { get; set; }
        public string DateOfSupply { get; set; }
        public string CINno { get; set; }
    }
}
