//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GSTR_ACTION_TYPE
    {
        public int ActionId { get; set; }
        public string ActionName { get; set; }
        public string GSTRType { get; set; }
    }
}
