//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HSN_MASTER
    {
        public int hsnId { get; set; }
        public string hsnCode { get; set; }
        public string hsnDescription { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> rowstatus { get; set; }
        public string hsnType { get; set; }
    
        public virtual TBL_Customer TBL_Customer { get; set; }
    }
}
