//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EWB_GEN_CONSOLIDATED
    {
        public int consewbid { get; set; }
        public string fromPlace { get; set; }
        public string fromState { get; set; }
        public string vehicleNo { get; set; }
        public string transMode { get; set; }
        public string transDocNo { get; set; }
        public string transDocDate { get; set; }
        public string status { get; set; }
        public string errorCodes { get; set; }
        public string cEwbNo { get; set; }
        public string cEWBDate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> CustId { get; set; }
    }
}
