//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AUTH_KEYS
    {
        public int KeyId { get; set; }
        public string Username { get; set; }
        public string AppKey { get; set; }
        public string EncryptedAppKey { get; set; }
        public string EncryptedOTP { get; set; }
        public string EncryptedSEK { get; set; }
        public string AuthToken { get; set; }
        public Nullable<int> Expiry { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AuthorizationToken { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> custid { get; set; }
    }
}
