//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Supplier
    {
        public int SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string POCName { get; set; }
        public string NatureOfBusiness { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string GSTINno { get; set; }
        public string StateCode { get; set; }
        public string PANNO { get; set; }
        public string DateofCompRegistered { get; set; }
        public string ConstitutionOfBusiness { get; set; }
        public string Address { get; set; }
        public int CustomerId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastmodifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> RowStatus { get; set; }
    }
}
