//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess_GSTIN
    {
        public int UserAccessId { get; set; }
        public int GSTINId { get; set; }
        public int CustId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> Rowstatus { get; set; }
    
        public virtual TBL_Cust_GSTIN TBL_Cust_GSTIN { get; set; }
        public virtual TBL_Customer TBL_Customer { get; set; }
        public virtual UserList UserList { get; set; }
    }
}
